name: sKeeland
author: Keeland
description: Skript Addon for Skript
version: 0.5.11
main: me.keeland.keelansk.Main
depend: [Skript]
softdepend: [Towny, GriefPrevention, ASkyBlock, WorldBorder, NexGenKoTHs, uSkyBlock, ProtocolLib, BloodMoon]